### ISSUE TITLE
System.Timers not in dotnet core

### ISSUE THREAD

**Issue by ctaggart** [fable-elmish/elmish#101]
The documentation at uses System.Timers
https://fable-elmish.github.io/elmish/subscriptions.html
https://github.com/fable-elmish/elmish/blob/master/docs/content/subscriptions.fsx
![image](https://user-images.githubusercontent.com/80104/27190216-09adf808-51f4-11e7-839c-48b152b57d6b.png)

That is not available for dotnet core:
https://docs.microsoft.com/en-us/dotnet/api/system.timers.timer

![image](https://user-images.githubusercontent.com/80104/27190305-55e8a358-51f4-11e7-9f33-05eaf66f862e.png)

What about using this instead?
https://docs.microsoft.com/en-us/dotnet/api/system.threading.timer

**Comment by ctaggart** [comment]
I tried:
``` fsharp
let timer initial =
    Cmd.ofSub (fun dispatch -> 
        let t = new System.Threading.Timer((fun _ -> dispatch (Msg.Time DateTime.Now)), null, 1000, System.Threading.Timeout.Infinite)
        ()
    )
```
but got:
```
error FABLE: Cannot find replacement for System.Threading.Timer::.ctor
```
:cry:

**Comment by ctaggart** [comment]
System.Timers will be supported with .NET Standard 2.0.
https://github.com/fable-compiler/Fable/issues/374

**Comment by et1975** [comment]
Interesting, 
I wrote that while Fable was still targeting full mono/.net, here's another way to get at a timer:
https://github.com/fable-elmish/sample-react-timer-svg/blob/master/src/App.fs#L21

Need to fix the docs.

@alfonsogarciacaro Fable probably should support `Threading.Timer`, since targeting NetStandard makes `System.Timers` useless.

**Comment by et1975** [comment]
Updated the docs to use window timer instead.
