### ISSUE TITLE
[discussion] Server-Side Rendering

### ISSUE THREAD

**Issue by maestrow** [fable-elmish/elmish#106]
Fable-Elmish core architecture is independent of renderers. So to build a browser web application we could use react or any other virtual DOM renderer. To realize server-side rendering with React we need to run node-server along with .net http server (i.e. Suave). As I can see - to avoid starting a node server, we need to develop our own Virtual DOM implementation, which could be rendered on the server, and then on the client side bind events to the rendered elements. 

Creating that Isomorphic Virtual DOM - Is this the right direction? I would like to discuss.

**Comment by et1975** [comment]
Could you elaborate on the benefits of server-rendered views in the context of elmish? I understand server-rendered React is a thing, but I admit I don't understand why.

**Comment by forki** [comment]
one of the things are search engines.

**Comment by johlrich** [comment]
I haven't used it personally, but there's JavaScriptServices which could allow you to manage the node usage from within dotnet instead of managing a separate service. There's a section about using it from non AspNetCore context also: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.NodeServices#for-non-aspnet-apps

I don't think there would be anything Fable-Elmish would need to do to enable this scenario too

**Comment by alfonsogarciacaro** [comment]
@forki Not entirely sure, but I think Google can already index SPAs.

I investigated a bit about server side rendering last year. With React you can do it using a node server so you can reuse your views in the frontend and render them as a string to build the HTML, then React on the frontend would just hook up the events. The benefit is the server would normally do the first render faster than the device, specially in comparison to low-budget mobile devices, so the user experience is supposedly better because users can see the content faster. However, at the time I couldn't find an elegant solution to pass the state from the server to the client (there was a hacky solution by serializing the state in a Pojo and putting it in a script tag) and it was also quite an amount of work for uncertain benefit.

Now the cool thing seem to be _Progressive Apps_. The [create-react-native scaffold does that](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app) and apparently it consists in creating an offline cache so the app can be used mostly without connection after the first download. I have to dig into that deeper but it doesn't look complicated: you [register a service worker](https://github.com/facebookincubator/create-react-app/blob/b98ba3d7ea21a7c0cb4e250559dbe0e44b89698c/packages/react-scripts/template/src/registerServiceWorker.js) that just checks if your requests ar cached or not. We could try to ~~copy~~ get inspiration from that approach.

**Comment by maestrow** [comment]
1. As for Progressive Web Apps, they also have an issue of [search engine indexing](https://www.searchenginejournal.com/get-progressive-web-apps-indexed-google-search/178209/). Solution is the same as with ordinary web applications - the content should be transmitted together with the application shell on the first request. This, in themselves, Progressive Web Apps are not a solution to server-side rendering task (as a way to solve search engine indexing problem). 

2. As for the state transfer. If the task is to transfer the state along with the content on the first page request, then I think we can use https://github.com/Zaid-Ajaj/Fable.Remoting to serialize / deserialize data. 

3. If use nodejs server (separately or with [NodeServices](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.NodeServices#for-non-aspnet-apps)), I do not understand how to pass view (an F# object three of DOM elements) to javascript code, executed in nodejs server. First the F# object three of DOM elements should translates to javascript to get a React components, then this should be passed to javascript code in node server to call `ReactDOMServer.renderToString(<MyComponent />);` ([example](https://www.npmjs.com/package/react-dom) of server-side rendering in React). The First step executed by Fable compiler, which is not a part of web app. So I think that this approach does not work. But may be I missunderstood something.

4. Among other things I care about React is the next question. From the React infrastructure, we can not get only VirtualDOM, the `react-dom` library depends on `react`. So we get ejs and a components factory  that we do not actually use. Those, we obtain an excessive functional/libs. Is not that bad?

5. Consider the option of writing a separate virtual DOM on F # to get server-side feature out of the box. Is it worth it? If yes, then how do you estimate the effort?

**Comment by alfonsogarciacaro** [comment]
There's already another Elmish renderer by @MangelMaxime based on the former fable-arch, but it still relies on JS VirtualDOM. But @mastoj had the idea of adapting the API to the HTML rendererer in Suave.Experimental so you could use more or less the same views on .NET. But still you would have to coordinate between the two renderers so the frontend can detect if the views are already rendered and then just hook up the events, which I assume is not a simple task.

Because of this, if we want to explore server-side rendering with Elmish probably the easiest way is to use also React on the backend (if .NET/JS interaction is not a problem), you'd have the same React views compiled to JS by Fable but on the server side they would be rendered to a string that would be returned to Suave or another .NET server.

About passing the state, serialization is not a problem (you can use Fable JSON serialization for that) but you don't want to force the frontend to ask for the state in this case: first, there'll be an extra call you could save and second, if the server doesn't cache you'll have to calculate the state twice (one for server-side rendering and another for responding to the client). What you want is somehow embedding the state in the server-side rendered HTML, usually with a `script` tag that puts the state in a global variable ([example](https://github.com/reactjs/redux/blob/master/docs/recipes/ServerRendering.md#inject-initial-component-html-and-state)).

**Comment by mastoj** [comment]
@alfonsogarciacaro is correct, but I didn't pursue a solution the problem. When I created the first dsl in fable-arch I did that as an improved dsl for that in suave, which I also has a large contribution to. However, the way everything was architected and lack of time prevented me to do something concrete.

It probably not a straightforward solution to the problem, but I do believe it should be doable.

**Comment by et1975** [comment]
I'm thinking there's two possible tracks here:

#### Server-side elmish loop
One could write a node server that uses server-side rendered React views. This is entirely doable albeit perhaps unnecessary.

#### Client-side elmish loop
I'm still not sure it makes sense, but If anyone wants to work on this:
- figure out what server-side-rendering `Program.setState` is going to do
- what does `dispatch` look like on server-side
- where does `update` run

I'm going to close this, but I if someone needs help with specific aspect of elmish I can help.
