### ISSUE TITLE
Access model from subscription

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-elmish/elmish#113]
The docs says
```fsharp
open Elmish
open Fable.Import.Browser

let timer initial =
    let sub dispatch = 
        window.setInterval(fun _ -> 
            dispatch (Tick DateTime.Now)
            , 1000) |> ignore
    Cmd.ofSub sub

Program.mkSimple init update (fun model _ -> printf "%A\n" model)
|> Program.withSubscription timer
|> Program.run
```
I need to access (the fresh current) model inside `setInterval` lambda. Is it possible?

**Comment by MangelMaxime** [comment]
No this is not according to the docs:

>  /// Subscribe to external source of events.
>    /// The subscription is called once - with the initial model, but can dispatch new messages at any time.

If you need to do something depending of the model state then you need to handle it in the `update` function. You can for example keep the subscription to dispatch a message every second. And in this message match over your model state.

Another solution could be to create a make the message dispatch itself in the update function after 1 second for example:

```fs
let delayMsg _ = 
  promise {
    do! promise.Sleep 1000
    return 1.
  }

let update msg model =
  match msg with
  | Tick tickValue ->
    let newModel = match model with | ......
    newModel, Cmd.ofPromise delayMsg () Tick ErrorMessage
```

The second solution can have the benefit of letting you stop the "timer" if you want.

**Comment by MangelMaxime** [comment]
Also, I believe accessing the model outside the update function would somehow break the "Elm architecture" concept.

**Comment by vasily-kirichenko** [comment]
Thanks! It works:
```fsharp
let update msg (model: Model) : Model =
    let formatTime (time: DateTime) = time.ToString "dd.MM.yyyy HH:mm:ss"
    match msg with
    | ...   
    | GetWeather dispatch ->
        promise {
            let! res = 
                tryFetch 
                    model.Url
                    [ RequestProperties.Mode RequestMode.Nocors
                      requestHeaders [ContentType "text/html"] ]

            match res with 
            | Ok response ->
                let! text = response.text()
                dispatch (GotWeather (DateTime.Now, text))
            | Error (e: exn) ->
                dispatch (FailedGotWeather (DateTime.Now, e.Message))
        } |> Promise.start
        model

let subscribe (_initial: Model) : Cmd<Msg> =
    fun (dispatch: Msg -> unit) ->
        window.setInterval ((fun _ -> dispatch (GetWeather dispatch)), 1000) |> ignore
    |> Cmd.ofSub
```
So I pass `dispatch` with a message. It works, but it's not synchronized due to asynchronicity (`Promise.start):

![1](https://user-images.githubusercontent.com/873919/30524013-5d9db99a-9bf4-11e7-9002-210157a0f21e.gif)

What I'd like to do is call the promise synchronously, like `Async.RunSynchronously`. Is it possible?

**Comment by alfonsogarciacaro** [comment]
Fable is not compatible with `Async.RunSynchronously` because there are things like HTTP requests which is not possible to run synchronously in JS.

There's a _dirty_ way to have access to the current model at any time. Just store a copy of it in the `update` function:

```fsharp
let mutable storedModel = None

let update msg (model: Model) : Model =
    let updatedModel = failwith "Model update"
    storedModel <- Some updatedModel
    updatedModel, []
```

Elmish gods will kill for recommending this, but JS is single-threaded so if you're sure nothing else modifies `storedModel` this ensures you to have always access to the latest model without racing issues. If you like to leave on the edge, you can also use `let mutable storedModel = Unchecked.defaultof<Model>` and set the stored model first in the `init` function ;)

**Comment by MangelMaxime** [comment]
@vasily-kirichenko You should use `Cmd.ofPromise` instead of start the promise yourself like that.

@alfonsogarciacaro Bravo now everyone will break their applications :D :D

**Comment by alfonsogarciacaro** [comment]
Hey, a man has to do what he has to do! :wink: @vasily-kirichenko please listen to @MangelMaxime, I'm still trying to master Elmish 👨‍🎓

**Comment by et1975** [comment]
`Cmd.ofSub` can be the way to pass the current state it in, but in general and in keeping with Elm's  Subscriptions, these are for handling the external events. For example, if timer is the source, let it feed the `Tick` message into your `update` function, which can combine it with the current state and something like `Cmd.ofPromise`, as @MangelMaxime suggests. 
Since @alfonsogarciacaro 's is the Fable god and supersedes Elmish gods in the divine hierarchy 
you can be sure it will work as advertised, but as always with deities, be careful of what you wish for :)

**Comment by vasily-kirichenko** [comment]
Thanks, guys. What I've ended up:

![image](https://user-images.githubusercontent.com/873919/30545729-29da8ba2-9c93-11e7-987e-fedb1710e9fb.png)

1. It starts with `GetWeather` command.
2. Dispatching it spawns a promise, which results with one of `GotWeather` or `FailedGotWeather` commands.
3. Dispatching either of the them results with `GetWeather` command again.
4. See #1.

It works, but it feels like an error prone approach, I mean it's very easy to forget to return `GetWeatcher` command as a result of all dispatcher branches and the periodic "loop" stops.

**Comment by MangelMaxime** [comment]
@vasily-kirichenko Personanlly, I would find it really clear. Because, in my head I see the Msg like a graph and know that each branch is handle correctly according to is state.

After, you could have use the `Subscription` to generate a `GetWeatcher` message every seconds. And just handle `GotWeather` and `FailedGotWeather` without calling back `GetWeather`. But then you can end up with several request in parallel which is not really useful.

**Comment by alfonsogarciacaro** [comment]
Actually I have a similar problem in my project, there are moments where you want to cancel the update function and enter in a _state machine_. There's a proposal by Tomas Petricek to [use async workflows to represent these state machines](https://msdn.microsoft.com/en-us/library/hh273070(v=vs.100).aspx) which I've explored in the past. It'd be nice to easily be able to cancel the message dispatching (or accumulate them in a buffer) an enter one such state machine. We could add a `Program` helper to do this, it shouldn't be difficult as Elmish itself [uses a MailboxProcessor internally](https://github.com/fable-elmish/elmish/blob/d708ddbc87b19a40046cf16e682ef99372a3b4fb/src/program.fs#L96-L110) which allows for running an asynchronous workflow when dealing with a message.

**Comment by vasily-kirichenko** [comment]
Thanks :) Now I'm sure I'm on the right track.

**Comment by et1975** [comment]
@alfonsogarciacaro , in my mind `update` is already a statemachine implementation. I'm a bit worried about "cancel the message dispatching" part, but I look forward to seeing what you have in mind. 
On the topic of doing something at most once, JS offers  `requestAnimationFrame` which React extensions [already utilize](https://github.com/fable-elmish/react/blob/master/src/react.fs#L20) for this purpose, perhaps this is something we can offer in a nicer shape as part of PowerPack?

**Comment by alfonsogarciacaro** [comment]
Actually, after looking at my own comment and the link, I guess the easiest way is to have an Elmish helper that allow for an asynchronous `update` function. In this case the messages won't be cancelled, just stored in the mailbox queue. Of course, care is needed in this case because the app won't be responsive until the update function is resolved, so maybe it's not desirable to have the helper available for everybody.

About `requestAnimationFrame` I saw that and I'm actually using it for the [soon-to-be `Program.withPhysicsWorker` helper](https://github.com/fable-compiler/fableconf-workshops/blob/4d1e526fde50290d14562850b51cabe925e43985/game/src/App/Elmish.Worker.fs) (don't tell anybody yet, it's a secret 🤐). We could add a `requestAnimationFrame` observable to Fable.Powerpack, but then we would be delegating the responsibility of keeping a model snapshot and calling `view` when appropriate to the user, and I guess this is better managed by Elmish itself (or an Elmish helper/extension).

**Comment by et1975** [comment]
Hey, web worker! Cool, I was thinking about running some parts of the dispatch loop in the worker, but the fact that one has to supply the url for the script instead of the script makes it hard to hide.
